apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: gcr.io/new-project-356711/calc:latest
          ports:
            - name: http1
              containerPort: 80
